services:
  app: 
    container_name: amazon-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command:
      - npm run dev
